; CCtrl firmware project configuration
[platformio]
default_envs = node_328p, master_esp32s3

[env]
framework = arduino
monitor_speed = 2000000

[env:node_328p]
platform = atmelavr
board = pro8MHzatmega328
board_build.f_cpu = 8000000L
upload_protocol = usbasp
upload_flags =
    -Pusb
    -B4
    -e
lib_deps =
    robtillaart/AS5600 @ ^0.6.4
    sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library @ ^1.2.12
build_src_filter =
    -<*>
    +<node/>
    +<shared/>

[env:master_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.f_cpu = 80000000L
upload_protocol = esptool
build_flags =
    -Iinclude
    -Ilib
    -Isrc
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    frankboesing/FastCRC @ ^1.41
    olikraus/U8g2 @ ^2.36.4
build_src_filter =
    -<*>
    +<master/>
    +<shared/>
    +<ui_runtime/>