#!/usr/bin/env python3
"""Convert a MIDI melody into a C++ PWM step list for ESP32 buzzer playback."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

import mido


@dataclass
class NoteEvent:
    start_ms: float
    end_ms: float
    note: int


@dataclass
class PwmStep:
    freq_hz: int
    duration_ms: int


def midi_note_to_freq_hz(note: int) -> int:
    return int(round(440.0 * (2.0 ** ((note - 69) / 12.0))))


def pick_source_track(mid: mido.MidiFile) -> int:
    if len(mid.tracks) == 1:
        return 0

    best_index = 0
    best_count = -1
    for idx, track in enumerate(mid.tracks):
        note_count = 0
        for msg in track:
            if msg.type == "note_on" and getattr(msg, "velocity", 0) > 0:
                note_count += 1
        if note_count > best_count:
            best_count = note_count
            best_index = idx
    return best_index


def extract_note_events(mid: mido.MidiFile, track_index: int) -> List[NoteEvent]:
    track = mid.tracks[track_index]
    tempo = 500000  # default: 120 BPM
    abs_ms = 0.0
    active_notes: Dict[int, float] = {}
    notes: List[NoteEvent] = []

    for msg in track:
        abs_ms += mido.tick2second(msg.time, mid.ticks_per_beat, tempo) * 1000.0

        if msg.type == "set_tempo":
            tempo = msg.tempo
            continue

        if msg.type == "note_on" and msg.velocity > 0:
            if msg.note in active_notes:
                start_ms = active_notes.pop(msg.note)
                if abs_ms > start_ms:
                    notes.append(NoteEvent(start_ms=start_ms, end_ms=abs_ms, note=msg.note))
            active_notes[msg.note] = abs_ms
            continue

        if msg.type == "note_off" or (msg.type == "note_on" and msg.velocity == 0):
            start_ms = active_notes.pop(msg.note, None)
            if start_ms is not None and abs_ms > start_ms:
                notes.append(NoteEvent(start_ms=start_ms, end_ms=abs_ms, note=msg.note))

    # Close dangling notes at the last known timestamp.
    for note, start_ms in active_notes.items():
        if abs_ms > start_ms:
            notes.append(NoteEvent(start_ms=start_ms, end_ms=abs_ms, note=note))

    notes.sort(key=lambda item: (item.start_ms, item.end_ms, item.note))
    return notes


def add_step(steps: List[PwmStep], freq_hz: int, duration_ms_float: float) -> None:
    duration_ms = int(round(duration_ms_float))
    if duration_ms <= 0:
        return

    if steps and steps[-1].freq_hz == freq_hz:
        steps[-1].duration_ms += duration_ms
    else:
        steps.append(PwmStep(freq_hz=freq_hz, duration_ms=duration_ms))


def to_pwm_steps(notes: List[NoteEvent], gap_ms: int) -> List[PwmStep]:
    steps: List[PwmStep] = []
    if not notes:
        return steps

    cursor_ms = 0.0
    for event in notes:
        start_ms = max(event.start_ms, cursor_ms)
        end_ms = max(event.end_ms, start_ms)

        # Explicitly model rests between note events as silent steps.
        if start_ms > cursor_ms:
            add_step(steps, 0, start_ms - cursor_ms)

        note_duration_ms = end_ms - start_ms
        if note_duration_ms <= 0.0:
            cursor_ms = end_ms
            continue

        play_ms = max(0.0, note_duration_ms - float(gap_ms))
        tail_rest_ms = note_duration_ms - play_ms

        if play_ms > 0.0:
            add_step(steps, midi_note_to_freq_hz(event.note), play_ms)
        if tail_rest_ms > 0.0:
            add_step(steps, 0, tail_rest_ms)

        cursor_ms = end_ms

    # Do not keep trailing silence after the last effective note.
    while steps and steps[-1].freq_hz == 0:
        steps.pop()

    return steps


def render_cpp_header(
    steps: List[PwmStep],
    midi_path: Path,
    track_index: int,
    gap_ms: int,
    output_var: str,
) -> str:
    total_ms = sum(step.duration_ms for step in steps)

    lines = [
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "// Generated by tools/midi_to_pwm_list.py.",
        f"// Source MIDI: {midi_path.name} (track {track_index})",
        f"// Notes are shortened by {gap_ms} ms to keep attack separation.",
        "struct BuzzerPwmStep {",
        "  uint16_t freq_hz;",
        "  uint32_t duration_ms;",
        "};",
        "",
        f"static const BuzzerPwmStep {output_var}[] = {{",
    ]

    for step in steps:
        lines.append(f"    {{{step.freq_hz}, {step.duration_ms}}},")

    lines.extend(
        [
            "};",
            "",
            f"static constexpr size_t {output_var}Count =",
            f"    sizeof({output_var}) / sizeof({output_var}[0]);",
            f"static constexpr uint32_t {output_var}TotalMs = {total_ms};",
            "",
        ]
    )

    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert MIDI notes into an ESP32 buzzer PWM C++ step table.",
    )
    parser.add_argument(
        "--input",
        default="ice.mid",
        help="Path to source MIDI file (default: ice.mid)",
    )
    parser.add_argument(
        "--output",
        default="src/ui_runtime/ice_melody_data.h",
        help="Path to generated C++ header file",
    )
    parser.add_argument(
        "--gap-ms",
        type=int,
        default=30,
        help="How much earlier each note ends to create separation (ms)",
    )
    parser.add_argument(
        "--track",
        type=int,
        default=-1,
        help="Track index to use. -1 means auto-select the track with most note_on events.",
    )
    parser.add_argument(
        "--var-name",
        default="kIceBootMelody",
        help="C++ array variable name",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    midi_path = Path(args.input)
    out_path = Path(args.output)

    if args.gap_ms < 0:
        raise ValueError("--gap-ms must be >= 0")

    mid = mido.MidiFile(midi_path)
    track_index = args.track if args.track >= 0 else pick_source_track(mid)

    if track_index >= len(mid.tracks):
        raise IndexError(f"Track index {track_index} out of range, file has {len(mid.tracks)} tracks")

    notes = extract_note_events(mid, track_index)
    steps = to_pwm_steps(notes, args.gap_ms)

    if not steps:
        raise RuntimeError("No effective note data found after parsing MIDI")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        render_cpp_header(
            steps=steps,
            midi_path=midi_path,
            track_index=track_index,
            gap_ms=args.gap_ms,
            output_var=args.var_name,
        ),
        encoding="utf-8",
    )

    print(f"Generated {out_path} with {len(steps)} steps")
    print(f"Total duration: {sum(step.duration_ms for step in steps)} ms")


if __name__ == "__main__":
    main()
